### ISSUE TITLE
Batch File hanging

### ISSUE THREAD

**Issue by simonPi2** [AmomentOfMusic/Zotero_scrivener_picker_windows#4]
Hi,

I installed Zotero Client on Windows 10, LibreOffice, Scrivener and the Zotero add-ons Better Bibtex and ODF Scan. 

I unzipped your file, created a new shortcut and linked the shortcut to Scrivener. Whole set-up was rebooted.

When I execute the link from scrivener or the shortcut/batch directly from your directory, I can select a Zotero source and submitt it but afterwards, the "DOS Window" where the batch is executed hangs with the message "Zotero is Running". No reference is inserted into Scrivener, also not after closure of the batch window.

Do you have any idea what could be missing?

Thanks - Best regards,

Simon

**Comment by AmomentOfMusic** [comment]
Hello Simon,

My first thought is to check whether or not ODF has indeed installed correctly - although I've heard that the issue should have fixed by the add-on creator recently, there have been numerous problems with the installer over the last couple.

Does scannable cite appear as an option when you look at Zotero's quick-copy default format? If not, that is probably your problem and you will have to install it manually 

See the link for instructions: 
https://forums.zotero.org/discussion/57428/scannable-cite-not-showing-up-in-zotero-standalone

Let me know if that solves the problem. Otherwise, I will play around and check a couple of other things...

**Comment by simonPi2** [comment]
Hi Emilie,

Thanks a lot for your quick reply! 
As it turned out, your first thought already resolved my problem; I just had to download the .js file and place it in the zotero\translators Folder (as I have the standalone version). Now, the citation appears ;-)

Many thanks again - I now have to quit this forum to start citing - Best regards,

Simon

**Comment by AmomentOfMusic** [comment]
Great! Glad to hear that was the issue. Maybe someday that issue will be fixed...

Happy citing,
Emilie
