### ISSUE TITLE
Shortcut, Scannable cite...

### ISSUE THREAD

**Issue by JulianSMoore** [AmomentOfMusic/Zotero_scrivener_picker_windows#6]
Hi Emilie

Followed the link from your reply to my post in the Scrivener forum. Thank you for this; I know how much effort is involved.

Two comments - one of which is an issue

1/ You say it doesn't matter where you put the zotpick folder, but you assume it goes in the Scrivener folder; it might be advisable to tell users that the shortcut needs to be repointed to the chosen location if they put it somewhere else

2/ The issue - I was pleasantly surprised that everything seemed to be working - Alt-Y, dialog, choose item, etc. - until it came time for Scrivener to actually insert and display the citation. Per your instructions (very good!) I checked for Scannable Cite in export options and it wasn't there. So, I followed the link and did a manual install (NB the target folder has to be Translators; that info is missing from the main - old - thread about scannable cite.js)

Unfortunately, despite quitting Zotero and FF and restarting, scannable cite doesn't show up (though I should say it is also not being removed from the Translators folder)

I enabled the debug log in zotero and restarted but I don't see any error messages related to scannable cite... this info is useful to record though

version => 5.0.96.2, platform => Win32, oscpu => Windows NT 10.0; WOW64, locale => en-GB, appName => Zotero, appVersion => 5.0.96.2, extensions => Zotero LibreOffice Integration (5.0.25.SA.5.0.96.2, extension), Zotero Word for Windows Integration (5.0.19.SA.5.0.96.2, extension), Better BibTex for Zotero (5.4.25, extension), ODF Scan for Zotero (2.0.43, extension)

(So it seems ODF scan is recognised here, as well as in the add-ons list)

(Actually there's no reference to any of the translators AFAICT in the debug log, so absence of Scannable Cite is not significant)

Sideloading scannable cite seemed to work for everyone else :( any ideas?

(Win 10 64-bit, up to date as of 30/06/2021)

**Comment by AmomentOfMusic** [comment]
Hi Julian,

per 1) thanks for the suggestion. Will consider updating the readme accordingly.

Per 2) Hmmm, that is strange. Just to make sure that scannable cite is indeed the issue, can you open up the script "scannable-cite.ps1" (it will open in notepad by default)  and edit this line, swapping out the portion that says "scannable-cite" for "formatted-citation"? (It will output whatever format you have selected as "default citation" in the export pane - also make sure not to delete the quotation mark at the end!)

`$ref = invoke-expression "curl 'http://localhost:23119/better-bibtex/cayw?format=scannable-cite' -usebasicparsing -userAgent 'USER'"`

Once you've changed that, makes sure to save and try calling the picker from scrivener and see if it inserts something. If it it does, then scannable cite is indeed the issue. If it is doesn't, let me know, and I can maybe help you do a bit more debugging to figure out the issue. 

If it is scannable cite: 

I'm not the developer of Scannable cite, so the most I can do is point you to some forum posts - one common issues seems to be downloading the raw code instead of the file itself. I would work your way through [this](https://forums.zotero.org/discussion/80689/scannable-cite)  post and [this](https://forums.zotero.org/discussion/57428/scannable-cite-not-showing-up-in-zotero-standalone) post and make sure you've followed all the suggestion there.

If still not working, then my suggestions would be to post to the Zotero forums - I'm afraid that my knowledge of how scannable cite works is fuzzy at best! I just leverage its uses for my purposes.

**Comment by JulianSMoore** [comment]
Hi,

I made the edit as suggested and lo and behold, a citation appeared, so it is scannable cite that is as fault.

Today I have problems with everything - zotero/scrivener/scannable-cite; jupyter/extensions/widgets.... I will be the #1 googler today!

Thanks for the extra links... If I resolve it I'll be sure to let you know.

J

**Comment by AmomentOfMusic** [comment]
Ah, that's a pain.... I wish you luck!

You mention jupyter, which suggests to me that you might be down with plaintext editing: if that is the case, the person who maintains [betterbibtext recently wrote a pandoc lua filte](https://retorque.re/zotero-better-bibtex/exporting/pandoc/)r that also results in live citations in word. So workflow would be scrivener > .md > docx via pandoc. Scrivener can even automatically call pandoc as part of the compilation process so that it's a one click process once set up (I haven't tried it yet, but definitely will at some point). You would then edit my picker script to output pandoc citations rather than scannable-cite. The main advantage being that you don't have to use libreoffice. 

Just thought I'd mention in case that sounds like a viable solution to you! I played around with the filter a couple of weeks ago and it does indeed work. If I were not so deep in my dissertation already I would probably switch to this workflow just to avoid libreoffice...

**Comment by JulianSMoore** [comment]
Don't worry, not asking for support but just in case anyone else comes across this...

Have failed miserably to resolve the "scannable cite" missing from Zotero... Preferences... Export... Default Format list under Export Formats I have now posted details to the [Zotero forum](https://forums.zotero.org/discussion/comment/377408?#) where all export translators are listed, together with the correspondence (failures) w.r.t. the Prefs... Export... dropdown list

(and thanks for the other suggestions! Feel free to close...)
