### ISSUE TITLE
Script breaks when there two Scrivener versions running (w. fix proposal)

### ISSUE THREAD

**Issue by ovojinovic** [AmomentOfMusic/Zotero_scrivener_picker_windows#7]
Hi,

Thank you for the elegant solution that works for us, poor Windows Scrivenerers! 
I've managed to break the script 😈. I realize this is a rare case, but the solution is rather simple, so you may consider include it in future releases.  

I have both Scrivener 1.9 and Scrivener 3 installed. I'm keeping old projects open in v.1 as a reference while writting a new manuscript in v.3. This breaks the script. 
I found that `(Get-Process Scrivener).MainWindowHandle` returns a list of two values instead of one (apparently both versions share the same name, "Scrivener"), and that breaks the call `(Get-Process Scrivener).MainWindowHandle`

An unelegant solution would be to index one of two elements:
`$ScrivenerHandle = (Get-Process Scrivener)[1].MainWindowHandle`
It may identify wrong process, not the wanted one, but in my (brief) experiment, it targets Scrivener 3, and the script does not break.

--
Oliver

**Comment by AmomentOfMusic** [comment]
Hi Oliver, 

Thanks for pointing out this edge case and for proposing a solution. Hadn't really thought about what would happen if you had both version open at once! I'll play around with your solution this weekend and probably push an update. 

I'm thinking the other way to get around is for the script to check what the active window is when it is called - this would also make it a somewhat more "universal" and usable with other programs... hmm, okay, will see what I can do.

Cheers,
Emilie

**Comment by ovojinovic** [comment]
> I'm thinking the other way to get around is for the script to check what the active window is when it is called - this would also make it a somewhat more "universal" and usable with other programs... 

That would be better approach, definitely. Just, please leave "Scrivener" in the title, so other Windows/Scrivener lost souls could still find it :)
BTW I've made a mistake, a solution would be to add an index to the call `[Zotero]::(Get-Process Scrivener)[1].MainWindowHandle`, not to the previous line. 

Regards,
Oliver

**Comment by AmomentOfMusic** [comment]
After saying I would get to it in a couple of days, I then promptly ignored this for a month! In any case, script has been updated to check for currently active window. I tested with both versions of Scrivener open at once and it seemed to work for me. That being said, the projects did not have the same name, so that is a potential stumbling block? In any case, I would love if you could try the newest version and see if it works for you.

Thanks for flagging this issue! - And don't worry, I'm keeping Scivener in the title for the sake of other "lost souls" (Of which I was once one, ha)
